### ISSUE TITLE
Is there a plan to release rest of evaluations?

### ISSUE THREAD

**Issue by msharmavikram** [filipradenovic/revisitop#1]
Appreciate in making this dataset available. 

I was wondering if you plan to release the other evaluations codebase to the community. Currently, I see that R-[37]-GeM is released. Is there any plan to release other? 

If not, perhaps, can you do release  DELF-ASMK*+SP, HesAff-rSIFT-ASMK*+SP, R-[10]-R-MAC+DFS?

**Comment by filipradenovic** [comment]
Most of the methods benchmarked in this project are available online:

- **R-[37]-GeM:** https://github.com/filipradenovic/cnnimageretrieval & https://github.com/filipradenovic/cnnimageretrieval-pytorch
- **R-[10]-R-MAC:** http://www.europe.naverlabs.com/Research/Computer-Vision/Learning-Visual-Representations/Deep-Image-Retrieval
- **DELF:** https://github.com/tensorflow/models/tree/master/research/delf
- **ASMK\*:** http://cmp.felk.cvut.cz/~toliageo/soft.html
- **HesAff:** https://github.com/perdoch/hesaff &  https://github.com/ducha-aiki/hesaff-pytorch (both contain SIFT implementation as well I believe)
- **rSIFT:** https://github.com/ducha-aiki/numpy-sift & https://github.com/ducha-aiki/pytorch-sift
- **DFS:** https://github.com/ahmetius/diffusion-retrieval & https://github.com/ducha-aiki/manifold-diffusion

I might have skipped or do not know of other implementations of the same methods. I am sure there are many more.

For now, we do not plan to release the unified evaluation of all the methods. Features for R-[37]-GeM are added to the code for the example evaluation purpose.

**Comment by msharmavikram** [comment]
Thanks! this helps to get started.

**Comment by Varshul** [comment]
Hey @filipradenovic. Great work on the paper and sharing of individual features.

Though for further evaluations would really be amazing if you can release features of `DELF-ASMK*+SP` (primarily) and others.

**Comment by filipradenovic** [comment]
This is a new implementation of DELF-ASMK* available: [github.com/gtolias/asmk](https://github.com/gtolias/asmk).
Additionally, there is a new implementation of HQE available: [github.com/gtolias/hqe](https://github.com/gtolias/hqe)

For now, we are not planning to release all the methods used in the paper, as many of them are already available online.
