### ISSUE TITLE
revisitop1m loading bug

### ISSUE THREAD

**Issue by shamangary** [filipradenovic/revisitop#3]
Hello @filipradenovic,

Thank you for providing the tool for accessing Oxford5k, Paris6k, and the revisited ones.
However, there is a bug in loading the distractor in the example file 'example_process_distractor.py'.

```
# Error
Traceback (most recent call last):
  File "example_process_distractors.py", line 42, in <module>
    cfg = configdataset(distractors_dataset, os.path.join(data_root, 'datasets'))
  File "/store/tsunyi/revisitop-master/python/dataset.py", line 11, in configdataset
    raise ValueError('Unknown dataset: {}!'.format(dataset))
ValueError: Unknown dataset: revisitop1m!
```
It is because 'configdataset' is adopted for getting the names.
```
config file for the dataset
cfg = configdataset(distractors_dataset, os.path.join(data_root, 'datasets'))

for i in np.arange(cfg['n']):
    im = pil_loader(cfg['im_fname'](cfg, i))
    ##------------------------------------------------------
    ## Perform image processing here, eg, feature extraction
    ##------------------------------------------------------
    print('>> {}: Processing image {}'.format(distractors_dataset, i+1))
```
However, revisitop1m does not share the same thing as ROxford5k, RParis6k,
and it does not need the label as well.

Therefore I provide an alternative to load them. 
```
import glob
from tqdm import tqdm

img_list = glob.glob('../data/datasets/revisitop1m/**/*.jpg', recursive=True)

for filename in tqdm(img_list):

    im = pil_loader(filename)
    ##------------------------------------------------------
    ## Perform image processing here, eg, feature extraction
    ##------------------------------------------------------
```

Thank you again for such an amazing project.

**Comment by filipradenovic** [comment]
Hey, this happened because I was refactoring the python code to use .pkl ground truth file with python dictionary instead of .mat files that were used before. While doing this, I forgot to handle the distractors set. Fixed in commit [`f5cf013`](https://github.com/filipradenovic/revisitop/commit/f5cf013cf5cced68c3488b82d7c827a6ba2d1ba7).
