### ISSUE TITLE
A quick question about R-[37]-GEM+DFS performance on ROxf and RPar

### ISSUE THREAD

**Issue by leejang** [filipradenovic/revisitop#5]
Hi Filip,

Thank you for making your code and dataset available! It's really good.

I have a one quick question. I tested "R-[37]-GEM+DFS" approach on the both ROxf and RPar datasets using the below git repository code and realized that these performance worked better than the performance you reported in your Revisiting paper published at CVPR 18.

https://github.com/ducha-aiki/manifold-diffusion

Here are the evaluation results.

Plain
>> roxford5k: mAP E: 84.81, M: 64.67, H: 38.47
>> roxford5k: mP@k[ 1  5 10] E: [97.06 92.06 86.49], M: [97.14 90.67 84.67], H: [81.43 63.   53.  ]
Diffusion cg
>> roxford5k: mAP E: 88.36, M: 74.4, H: 50.57
>> roxford5k: mP@k[ 1  5 10] E: [95.59 93.82 91.39], M: [95.71 92.86 88.14], H: [88.57 70.29 61.29]
Diffusion trunkated
>> roxford5k: mAP E: 88.18, M: 74.33, H: 50.7
>> roxford5k: mP@k[ 1  5 10] E: [95.59 93.82 91.39], M: [95.71 92.86 88.14], H: [88.57 70.29 61.29]
Spectral R=2000
>> roxford5k: mAP E: 86.5, M: 72.0, H: 45.7
>> roxford5k: mP@k[ 1  5 10] E: [94.12 92.65 91.3 ], M: [94.29 91.14 87.86], H: [81.43 72.43 61.29]

Plain
>> rparis6k: mAP E: 92.12, M: 77.2, H: 56.32
>> rparis6k: mP@k[ 1  5 10] E: [100.    97.14  96.14], M: [100.    98.86  98.14], H: [94.29 90.29 89.14]
Diffusion cg
>> rparis6k: mAP E: 94.72, M: 89.63, H: 80.01
>> rparis6k: mP@k[ 1  5 10] E: [100.    97.43  95.86], M: [100.    99.43  98.57], H: [95.71 91.14 91.43]
Diffusion trunkated
>> rparis6k: mAP E: 94.73, M: 89.64, H: 80.03
>> rparis6k: mP@k[ 1  5 10] E: [100.    97.43  95.86], M: [100.    99.43  98.57], H: [95.71 91.14 91.29]
Spectral R=2000
>> rparis6k: mAP E: 93.61, M: 85.42, H: 73.31
>> rparis6k: mP@k[ 1  5 10] E: [98.57 96.29 95.95], M: [100.    98.86  98.86], H: [92.86 90.86 91.71]

Could you please let me know why the results are difference between the results you reported and the results that I got using the code?

Thanks you.

Best,
Jangwon

**Comment by filipradenovic** [comment]
Code used in the paper is the [original implementation in MATLAB](https://github.com/ahmetius/diffusion-retrieval).

There could be a difference in parameter setting, or something like that. You can contact the author of the [Python reimplementation](https://github.com/ducha-aiki/manifold-diffusion). @ducha-aiki, do you know the reason?

**Comment by leejang** [comment]
Thanks for this quick response Filip!  I appreciate it.
Yes, it seems that it happened because of the difference parameter setting. I changed the the parameter setting according to your original MATLAB implementation, then got the similar results that you reported in the paper.

Plain
>> rparis6k: mAP E: 92.12, M: 77.2, H: 56.32
>> rparis6k: mP@k[ 1  5 10] E: [100.    97.14  96.14], M: [100.    98.86  98.14], H: [94.29 90.29 89.14]
Diffusion cg
>> rparis6k: mAP E: 93.61, M: 88.63, H: 78.32
>> rparis6k: mP@k[ 1  5 10] E: [98.57 96.   94.1 ], M: [100.    97.14  96.  ], H: [95.71 93.71 93.43]
Diffusion trunkated
>> rparis6k: mAP E: 94.99, M: 89.74, H: 80.1
>> rparis6k: mP@k[ 1  5 10] E: [100.    97.71  95.52], M: [100.    99.43  97.57], H: [95.71 94.29 94.29]
Spectral R=2000
>> rparis6k: mAP E: 93.48, M: 88.4, H: 77.62
>> rparis6k: mP@k[ 1  5 10] E: [97.14 95.43 94.38], M: [97.14 96.57 96.43], H: [92.86 94.   93.86]

Hi @ducha-aiki, could you please please let me know if there is other reason?

Thank you.

Best,
Jangwon

**Comment by ducha-aiki** [comment]
Hi @leejang 
I believe that the difference is mainly parameters setup. I tuned it to have the best performance on the small subset of Google Retrieval Challenge on kaggle previous year.

**Comment by leejang** [comment]
Thanks for letting me know @ducha-aiki ! It makes sense to me.

I am going to close this question.

Thanks @ducha-aiki and @filipradenovic !

Best,
Jangwon
